/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapReviewsDotxmlRouteImport } from './routes/sitemap-reviews[.]xml'
import { Route as SitemapGuidesDotxmlRouteImport } from './routes/sitemap-guides[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NoteLegaliRouteImport } from './routes/note-legali'
import { Route as GuidaRtpRouteImport } from './routes/guida-rtp'
import { Route as GiocoResponsabileRouteImport } from './routes/gioco-responsabile'
import { Route as ComeRegistrarsiRouteImport } from './routes/come-registrarsi'
import { Route as CasinoPaypalRouteImport } from './routes/casino-paypal'
import { Route as BonusSenzaDepositoRouteImport } from './routes/bonus-senza-deposito'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderSlugRouteImport } from './routes/provider.$slug'
import { Route as OperatoriSlugRouteImport } from './routes/operatori.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapReviewsDotxmlRoute = SitemapReviewsDotxmlRouteImport.update({
  id: '/sitemap-reviews.xml',
  path: '/sitemap-reviews.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapGuidesDotxmlRoute = SitemapGuidesDotxmlRouteImport.update({
  id: '/sitemap-guides.xml',
  path: '/sitemap-guides.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteLegaliRoute = NoteLegaliRouteImport.update({
  id: '/note-legali',
  path: '/note-legali',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidaRtpRoute = GuidaRtpRouteImport.update({
  id: '/guida-rtp',
  path: '/guida-rtp',
  getParentRoute: () => rootRouteImport,
} as any)
const GiocoResponsabileRoute = GiocoResponsabileRouteImport.update({
  id: '/gioco-responsabile',
  path: '/gioco-responsabile',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeRegistrarsiRoute = ComeRegistrarsiRouteImport.update({
  id: '/come-registrarsi',
  path: '/come-registrarsi',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoPaypalRoute = CasinoPaypalRouteImport.update({
  id: '/casino-paypal',
  path: '/casino-paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusSenzaDepositoRoute = BonusSenzaDepositoRouteImport.update({
  id: '/bonus-senza-deposito',
  path: '/bonus-senza-deposito',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderSlugRoute = ProviderSlugRouteImport.update({
  id: '/provider/$slug',
  path: '/provider/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatoriSlugRoute = OperatoriSlugRouteImport.update({
  id: '/operatori/$slug',
  path: '/operatori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonus-senza-deposito': typeof BonusSenzaDepositoRoute
  '/casino-paypal': typeof CasinoPaypalRoute
  '/come-registrarsi': typeof ComeRegistrarsiRoute
  '/gioco-responsabile': typeof GiocoResponsabileRoute
  '/guida-rtp': typeof GuidaRtpRoute
  '/note-legali': typeof NoteLegaliRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-guides.xml': typeof SitemapGuidesDotxmlRoute
  '/sitemap-reviews.xml': typeof SitemapReviewsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/operatori/$slug': typeof OperatoriSlugRoute
  '/provider/$slug': typeof ProviderSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bonus-senza-deposito': typeof BonusSenzaDepositoRoute
  '/casino-paypal': typeof CasinoPaypalRoute
  '/come-registrarsi': typeof ComeRegistrarsiRoute
  '/gioco-responsabile': typeof GiocoResponsabileRoute
  '/guida-rtp': typeof GuidaRtpRoute
  '/note-legali': typeof NoteLegaliRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-guides.xml': typeof SitemapGuidesDotxmlRoute
  '/sitemap-reviews.xml': typeof SitemapReviewsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/operatori/$slug': typeof OperatoriSlugRoute
  '/provider/$slug': typeof ProviderSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonus-senza-deposito': typeof BonusSenzaDepositoRoute
  '/casino-paypal': typeof CasinoPaypalRoute
  '/come-registrarsi': typeof ComeRegistrarsiRoute
  '/gioco-responsabile': typeof GiocoResponsabileRoute
  '/guida-rtp': typeof GuidaRtpRoute
  '/note-legali': typeof NoteLegaliRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-guides.xml': typeof SitemapGuidesDotxmlRoute
  '/sitemap-reviews.xml': typeof SitemapReviewsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/operatori/$slug': typeof OperatoriSlugRoute
  '/provider/$slug': typeof ProviderSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bonus-senza-deposito'
    | '/casino-paypal'
    | '/come-registrarsi'
    | '/gioco-responsabile'
    | '/guida-rtp'
    | '/note-legali'
    | '/privacy'
    | '/sitemap-guides.xml'
    | '/sitemap-reviews.xml'
    | '/sitemap.xml'
    | '/operatori/$slug'
    | '/provider/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bonus-senza-deposito'
    | '/casino-paypal'
    | '/come-registrarsi'
    | '/gioco-responsabile'
    | '/guida-rtp'
    | '/note-legali'
    | '/privacy'
    | '/sitemap-guides.xml'
    | '/sitemap-reviews.xml'
    | '/sitemap.xml'
    | '/operatori/$slug'
    | '/provider/$slug'
  id:
    | '__root__'
    | '/'
    | '/bonus-senza-deposito'
    | '/casino-paypal'
    | '/come-registrarsi'
    | '/gioco-responsabile'
    | '/guida-rtp'
    | '/note-legali'
    | '/privacy'
    | '/sitemap-guides.xml'
    | '/sitemap-reviews.xml'
    | '/sitemap.xml'
    | '/operatori/$slug'
    | '/provider/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BonusSenzaDepositoRoute: typeof BonusSenzaDepositoRoute
  CasinoPaypalRoute: typeof CasinoPaypalRoute
  ComeRegistrarsiRoute: typeof ComeRegistrarsiRoute
  GiocoResponsabileRoute: typeof GiocoResponsabileRoute
  GuidaRtpRoute: typeof GuidaRtpRoute
  NoteLegaliRoute: typeof NoteLegaliRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapGuidesDotxmlRoute: typeof SitemapGuidesDotxmlRoute
  SitemapReviewsDotxmlRoute: typeof SitemapReviewsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OperatoriSlugRoute: typeof OperatoriSlugRoute
  ProviderSlugRoute: typeof ProviderSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-reviews.xml': {
      id: '/sitemap-reviews.xml'
      path: '/sitemap-reviews.xml'
      fullPath: '/sitemap-reviews.xml'
      preLoaderRoute: typeof SitemapReviewsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-guides.xml': {
      id: '/sitemap-guides.xml'
      path: '/sitemap-guides.xml'
      fullPath: '/sitemap-guides.xml'
      preLoaderRoute: typeof SitemapGuidesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note-legali': {
      id: '/note-legali'
      path: '/note-legali'
      fullPath: '/note-legali'
      preLoaderRoute: typeof NoteLegaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guida-rtp': {
      id: '/guida-rtp'
      path: '/guida-rtp'
      fullPath: '/guida-rtp'
      preLoaderRoute: typeof GuidaRtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioco-responsabile': {
      id: '/gioco-responsabile'
      path: '/gioco-responsabile'
      fullPath: '/gioco-responsabile'
      preLoaderRoute: typeof GiocoResponsabileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/come-registrarsi': {
      id: '/come-registrarsi'
      path: '/come-registrarsi'
      fullPath: '/come-registrarsi'
      preLoaderRoute: typeof ComeRegistrarsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino-paypal': {
      id: '/casino-paypal'
      path: '/casino-paypal'
      fullPath: '/casino-paypal'
      preLoaderRoute: typeof CasinoPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus-senza-deposito': {
      id: '/bonus-senza-deposito'
      path: '/bonus-senza-deposito'
      fullPath: '/bonus-senza-deposito'
      preLoaderRoute: typeof BonusSenzaDepositoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$slug': {
      id: '/provider/$slug'
      path: '/provider/$slug'
      fullPath: '/provider/$slug'
      preLoaderRoute: typeof ProviderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operatori/$slug': {
      id: '/operatori/$slug'
      path: '/operatori/$slug'
      fullPath: '/operatori/$slug'
      preLoaderRoute: typeof OperatoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BonusSenzaDepositoRoute: BonusSenzaDepositoRoute,
  CasinoPaypalRoute: CasinoPaypalRoute,
  ComeRegistrarsiRoute: ComeRegistrarsiRoute,
  GiocoResponsabileRoute: GiocoResponsabileRoute,
  GuidaRtpRoute: GuidaRtpRoute,
  NoteLegaliRoute: NoteLegaliRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapGuidesDotxmlRoute: SitemapGuidesDotxmlRoute,
  SitemapReviewsDotxmlRoute: SitemapReviewsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OperatoriSlugRoute: OperatoriSlugRoute,
  ProviderSlugRoute: ProviderSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
